### ISSUE TITLE
Harlequin --config crashes if adapters do not declare options

### ISSUE THREAD

**Issue by rupurt** [tconbeer/harlequin#404]
I'm managed to get harlequin running linked to unixodbc without errors so can successfully load the UI. Thank you!

However, when trying to setup a config file I get the following error

```shell
Traceback (most recent call last):
  File "/Users/alex/workspace/mechanical-orchard/evac/.venv/bin/harlequin", line 8, in <module>
    sys.exit(harlequin())
             ^^^^^^^^^^^
  File "/Users/alex/workspace/mechanical-orchard/evac/.venv/lib/python3.11/site-packages/harlequin/cli.py", line 297, in harlequin
    cli()
  File "/Users/alex/workspace/mechanical-orchard/evac/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alex/workspace/mechanical-orchard/evac/.venv/lib/python3.11/site-packages/rich_click/rich_command.py", line 125, in main
    with self.make_context(prog_name, args, **extra) as ctx:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alex/workspace/mechanical-orchard/evac/.venv/lib/python3.11/site-packages/click/core.py", line 943, in make_context
    self.parse_args(ctx, args)
  File "/Users/alex/workspace/mechanical-orchard/evac/.venv/lib/python3.11/site-packages/click/core.py", line 1408, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alex/workspace/mechanical-orchard/evac/.venv/lib/python3.11/site-packages/click/core.py", line 2400, in handle_parse_result
    value = self.process_value(ctx, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alex/workspace/mechanical-orchard/evac/.venv/lib/python3.11/site-packages/click/core.py", line 2362, in process_value
    value = self.callback(ctx, self, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alex/workspace/mechanical-orchard/evac/.venv/lib/python3.11/site-packages/harlequin/cli.py", line 110, in _config_wizard_callback
    wizard()
  File "/Users/alex/workspace/mechanical-orchard/evac/.venv/lib/python3.11/site-packages/harlequin/config_wizard.py", line 25, in wizard
    _wizard()
  File "/Users/alex/workspace/mechanical-orchard/evac/.venv/lib/python3.11/site-packages/harlequin/config_wizard.py", line 91, in _wizard
    which = questionary.checkbox(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alex/workspace/mechanical-orchard/evac/.venv/lib/python3.11/site-packages/questionary/prompts/checkbox.py", line 132, in checkbox
    ic = InquirerControl(
         ^^^^^^^^^^^^^^^^
  File "/Users/alex/workspace/mechanical-orchard/evac/.venv/lib/python3.11/site-packages/questionary/prompts/common.py", line 273, in __init__
    if not self.is_selection_valid():
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alex/workspace/mechanical-orchard/evac/.venv/lib/python3.11/site-packages/questionary/prompts/common.py", line 442, in is_selection_valid
    return not self.is_selection_disabled() and not self.is_selection_a_separator()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alex/workspace/mechanical-orchard/evac/.venv/lib/python3.11/site-packages/questionary/prompts/common.py", line 439, in is_selection_disabled
    return self.choices[self.pointed_at].disabled
                        ^^^^^^^^^^^^^^^
AttributeError: 'InquirerControl' object has no attribute 'pointed_at'. Did you mean: 'get_pointed_at'?
```

**Comment by tconbeer** [comment]
Patched in harlequin v1.10.0

**Comment by rupurt** [comment]
That fixed the config generator. Thanks!

Unfortunately it can't seem to connect yet. I can confirm it works with `pyodbc`. It gets stuck on a loader screen.

<img width="1512" alt="Screenshot 2024-01-11 at 4 07 04 PM" src="https://github.com/tconbeer/harlequin/assets/680789/02a8a707-9768-47a7-84f1-cfab12c36fc1">

**.harlequin.toml**

```toml
default_profile = "testdb"

[profiles.testdb]
adapter = "odbc"
theme = "harlequin"
limit = 100000
conn_str = [
  "Driver=/nix/store/2ahm9s641yjxw3v3ra5v074ba6yp4zwh-db2-odbc-driver-11.5.8/lib/libdb2.dylib;Hostname=localhost;Database=testdb;Uid=db2inst1;Pwd=password;Port=50000"
]
```

**Comment by rupurt** [comment]
My bad! It just took a really long time to load the catalog. I can confirm it works!!! You da man @tconbeer.

Thank you for adding this adapter so quickly 🙏 

<img width="1512" alt="Screenshot 2024-01-11 at 4 19 42 PM" src="https://github.com/tconbeer/harlequin/assets/680789/3f68179e-344a-4eb1-9ff7-6f2b6a1db798">
