### ISSUE TITLE
Add support for Python 3.13

### ISSUE THREAD

**Issue by tconbeer** [tconbeer/harlequin#697]
Looks like tree-sitter may have added 3.13 support, but now I get a numpy issue:

```
~ ❯ uvx --python 3.13 harlequin
Installed 28 packages in 24ms
Traceback (most recent call last):
  File "/home/tco/.cache/uv/archive-v0/93PFvqkKWBiASxR8fuac-/bin/harlequin", line 7, in <module>
    from harlequin.cli import harlequin
  File "/home/tco/.cache/uv/archive-v0/93PFvqkKWBiASxR8fuac-/lib/python3.13/site-packages/harlequin/__init__.py", line 1, in <module>
    from harlequin.app import Harlequin as Harlequin
  File "/home/tco/.cache/uv/archive-v0/93PFvqkKWBiASxR8fuac-/lib/python3.13/site-packages/harlequin/app.py", line 23, in <module>
    from harlequin.adapter import HarlequinAdapter, HarlequinCursor
  File "/home/tco/.cache/uv/archive-v0/93PFvqkKWBiASxR8fuac-/lib/python3.13/site-packages/harlequin/adapter.py", line 7, in <module>
    from textual_fastdatatable.backend import AutoBackendType
  File "/home/tco/.cache/uv/archive-v0/93PFvqkKWBiASxR8fuac-/lib/python3.13/site-packages/textual_fastdatatable/__init__.py", line 1, in <module>
    from textual_fastdatatable.backend import (
    ...<4 lines>...
    )
  File "/home/tco/.cache/uv/archive-v0/93PFvqkKWBiASxR8fuac-/lib/python3.13/site-packages/textual_fastdatatable/backend.py", line 7, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

This is the culprit:

https://github.com/tconbeer/textual-fastdatatable/blob/29d492346e7e3be1c5cf21aedbc2c804873be693/pyproject.toml#L31-L32

_Originally posted by @tconbeer in https://github.com/tconbeer/harlequin/discussions/670#discussioncomment-11325666_

**Comment by darrenburns** [comment]
Hey Ted - I'm looking at this now from the Textual side. Can't promise anything but hopefully we'll be able to support 3.13 soon.

**Comment by darrenburns** [comment]
Support for syntax highlighting on Python 3.13 is in `main` in Textual now and should be released in the coming days.

Note that the new version of tree-sitter drops support for Python 3.8.

There's been a necessary few changes to the highlighting too which may affect Harlequin if you use the builtin SQL highlighting, so I recommend giving it a spin first. Let me know if there's any issues!

**Comment by tconbeer** [comment]
Thanks so much, @darrenburns !

**Comment by darrenburns** [comment]
This is out now in the latest Textual release.

**Comment by ryanb8** [comment]
When installing with `uv tool install --python 3.13 harlequin`, I had to move to use `uv tool install --python 3.13 --with numpy harlequin`. 


It installed fine with the first command, but couldn't actually find numpy at runtime (with a similar `ModuleNotFoundError: No module named 'numpy'` error as this issue originally started with).

**Comment by tconbeer** [comment]
The latest commit on main supports 3.13; the latest release does not. Hoping to wrap one more breaking change into main and then release as 2.0. Maybe this week, we'll see.

**Comment by ryanb8** [comment]
Got it - thank you!
