### ISSUE TITLE
Homebrew install issues with M3 arm64 architecture

### ISSUE THREAD

**Issue by heuermh** [tconbeer/harlequin#699]
**Before Proceeding, please acknowledge**:
- [x] I have consulted the [Troubleshooting guide](https://harlequin.sh/docs/troubleshooting/index).
- [x] I have searched Issues and Discussions in this repo.
- [x] Feature requests should be initiated as Discussions. This is a bug report.

**Describe the bug**

Not sure if best to create an issue here or at Homebrew.

The first attempt failed with `Reinstalling 1 dependent with broken linkage from source`, the second attempt installed an executable but it appears to be missing some `apache-arrow` dependencies.

```bash
$ brew install harlequin
==> Downloading https://ghcr.io/v2/homebrew/core/harlequin/manifests/1.25.2
############################################################################################################################################################## 100.0%
==> Fetching dependencies for harlequin: aws-sdk-cpp, re2, grpc, snappy, thrift, utf8proc, apache-arrow and python@3.11
...
==> Fetching harlequin
==> Downloading https://ghcr.io/v2/homebrew/core/harlequin/blobs/sha256:431c1d2d62756ffe35844622de0752cd921442607dc4053dbeeb3df4cb48c05d
############################################################################################################################################################## 100.0%
==> Installing dependencies for harlequin: aws-sdk-cpp, re2, grpc, snappy, thrift, utf8proc, apache-arrow and python@3.11
...
==> Installing harlequin
==> Pouring harlequin--1.25.2.arm64_sonoma.bottle.tar.gz
🍺  /opt/homebrew/Cellar/harlequin/1.25.2: 3,361 files, 101.8MB
==> Running `brew cleanup harlequin`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> No outdated dependents to upgrade!
==> Checking for dependents of upgraded formulae...
Disable this behaviour by setting HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Reinstalling 1 dependent with broken linkage from source:
harlequin

$ harlequin
-bash: harlequin: command not found

$ brew install harlequin
==> Downloading https://ghcr.io/v2/homebrew/core/harlequin/manifests/1.25.2
Already downloaded: /Users/xxx/Library/Caches/Homebrew/downloads/3494fa1508f5ec620002e3a359fadb666cc8cdda625530d26b972800d6816dcb--harlequin-1.25.2.bottle_manifest.json
==> Fetching harlequin
==> Downloading https://ghcr.io/v2/homebrew/core/harlequin/blobs/sha256:431c1d2d62756ffe35844622de0752cd921442607dc4053dbeeb3df4cb48c05d
Already downloaded: /Users/xxx/Library/Caches/Homebrew/downloads/a1b7b4348ac005485d0455895e9e61d16485b110bc0903e583e9fb93134a2044--harlequin--1.25.2.arm64_sonoma.bottle.tar.gz
==> Pouring harlequin--1.25.2.arm64_sonoma.bottle.tar.gz
🍺  /opt/homebrew/Cellar/harlequin/1.25.2: 3,361 files, 101.8MB
==> Running `brew cleanup harlequin`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

$ harlequin
Traceback (most recent call last):
  File "/opt/homebrew/bin/harlequin", line 5, in <module>
    from harlequin.cli import harlequin
  File "/opt/homebrew/Cellar/harlequin/1.25.2/libexec/lib/python3.11/site-packages/harlequin/__init__.py", line 1, in <module>
    from harlequin.adapter import HarlequinAdapter, HarlequinConnection, HarlequinCursor
  File "/opt/homebrew/Cellar/harlequin/1.25.2/libexec/lib/python3.11/site-packages/harlequin/adapter.py", line 7, in <module>
    from textual_fastdatatable.backend import AutoBackendType
  File "/opt/homebrew/Cellar/harlequin/1.25.2/libexec/lib/python3.11/site-packages/textual_fastdatatable/__init__.py", line 1, in <module>
    from textual_fastdatatable.backend import (
  File "/opt/homebrew/Cellar/harlequin/1.25.2/libexec/lib/python3.11/site-packages/textual_fastdatatable/backend.py", line 17, in <module>
    import pyarrow as pa
  File "/opt/homebrew/Cellar/harlequin/1.25.2/libexec/lib/python3.11/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
ImportError: dlopen(/opt/homebrew/Cellar/harlequin/1.25.2/libexec/lib/python3.11/site-packages/pyarrow/lib.cpython-311-darwin.so, 0x0002): Library not loaded: /opt/homebrew/opt/apache-arrow/lib/libarrow_dataset.1800.dylib
  Referenced from: <F0CDA121-6C5D-3E63-99AF-3720A44F7F8E> /opt/homebrew/Cellar/harlequin/1.25.2/libexec/lib/python3.11/site-packages/pyarrow/lib.cpython-311-darwin.so
  Reason: tried: '/opt/homebrew/opt/apache-arrow/lib/libarrow_dataset.1800.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/apache-arrow/lib/libarrow_dataset.1800.dylib' (no such file), '/opt/homebrew/opt/apache-arrow/lib/libarrow_dataset.1800.dylib' (no such file), '/opt/homebrew/Cellar/apache-arrow/18.1.0/lib/libarrow_dataset.1800.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/apache-arrow/18.1.0/lib/libarrow_dataset.1800.dylib' (no such file), '/opt/homebrew/Cellar/apache-arrow/18.1.0/lib/libarrow_dataset.1800.dylib' (no such file)
```

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Actual behavior**
A clear and concise description of what happened; please include screenshots or videos of Harlequin if possible.

**Contributing**
Are you interested in contributing a fix?
- [ ] Yes
- [x] Maybe
- [ ] No

**Additional context**
*Please provide as much as you can, but don't waste your time if it's definitely not relevant or you don't know.*

What is the output of `harlequin --version`?

What database adapter are you using with Harlequin? (Default is `duckdb`)

What other options are you using when invoking Harlequin? (If you are using a profile, please add relevant items from your profile here).

Can you tell us more about your system?

```bash
$ uname -a
Darwin xxx.domain 23.6.0 Darwin Kernel Version 23.6.0: Wed Jul 31 20:50:54 PDT 2024; root:xnu-10063.141.1.700.5~1/RELEASE_ARM64_T8122 arm64
```

How did you install Harlequin?
- [ ] pipx
- [ ] conda/mamba
- [ ] pip (global install)
- [ ] pip + venv/virtualenv or pipenv
- [ ] Poetry
- [ ] uv/Rye
- [x] other:  Homebrew

**Comment by tconbeer** [comment]
I didn't know there was a homebrew formula for Harlequin and I don't maintain it.

**Comment by tconbeer** [comment]
Apparently it's new as of yesterday: https://github.com/Homebrew/homebrew-core/pull/198108

**Comment by tconbeer** [comment]
I recommend opening an issue in Homebrew and tagging @mfinelli

**Comment by heuermh** [comment]
Thanks, will do!

**Comment by mfinelli** [comment]
I suspect this is because harlequin was bottled with apache-arrow 18.0.0, but 18.1.0 was released but the harlequin wasn't rebuilt and rebottled against the new version. Does it work if you brew install --build-from-source?

**Comment by heuermh** [comment]
> Does it work if you brew install --build-from-source?

Yes, I had/have `apache-arrow` 18.1.0 installed, and `--build-from-source` worked
```
$ brew uninstall --force harlequin
$ brew install harlequin --build-from-source
...
==> Pouring apache-arrow--18.1.0.arm64_sonoma.bottle.tar.gz
🍺  /opt/homebrew/Cellar/apache-arrow/18.1.0: 596 files, 113.9MB
==> Installing harlequin
==> python3.11 -m venv --system-site-packages --without-pip /opt/homebrew/Cellar/harlequin/1.25.2_1/libexec
==> python3.11 -m pip --python=/opt/homebrew/Cellar/harlequin/1.25.2_1/libexec/bin/python install /private/tmp/harlequin--cython-20241129-47
==> python3.11 -m pip --python=/opt/homebrew/Cellar/harlequin/1.25.2_1/libexec/bin/python install /private/tmp/harlequin--meson-python-20241
==> python3.11 -m pip --python=/opt/homebrew/Cellar/harlequin/1.25.2_1/libexec/bin/python install /private/tmp/harlequin--click-20241129-478
==> python3.11 -m pip --python=/opt/homebrew/Cellar/harlequin/1.25.2_1/libexec/bin/python install /private/tmp/harlequin--duckdb-20241129-47
==> python3.11 -m pip --python=/opt/homebrew/Cellar/harlequin/1.25.2_1/libexec/bin/python install /private/tmp/harlequin--Jinja2-20241129-47
==> python3.11 -m pip --python=/opt/homebrew/Cellar/harlequin/1.25.2_1/libexec/bin/python install /private/tmp/harlequin--linkify-it-py-2024
==> python3.11 -m pip --python=/opt/homebrew/Cellar/harlequin/1.25.2_1/libexec/bin/python install /private/tmp/harlequin--markdown-it-py-202
==> python3.11 -m pip --python=/opt/homebrew/Cellar/harlequin/1.25.2_1/libexec/bin/python install /private/tmp/harlequin--MarkupSafe-2024112
==> python3.11 -m pip --python=/opt/homebrew/Cellar/harlequin/1.25.2_1/libexec/bin/python install /private/tmp/harlequin--mdit-py-plugins-20
==> python3.11 -m pip --python=/opt/homebrew/Cellar/harlequin/1.25.2_1/libexec/bin/python install /private/tmp/harlequin--mdurl-20241129-478
==> python3.11 -m pip --python=/opt/homebrew/Cellar/harlequin/1.25.2_1/libexec/bin/python install /private/tmp/harlequin--numpy-20241129-478
==> python3.11 -m pip --python=/opt/homebrew/Cellar/harlequin/1.25.2_1/libexec/bin/python install /private/tmp/harlequin--platformdirs-20241
==> python3.11 -m pip --python=/opt/homebrew/Cellar/harlequin/1.25.2_1/libexec/bin/python install /private/tmp/harlequin--prompt-toolkit-202
==> python3.11 -m pip --python=/opt/homebrew/Cellar/harlequin/1.25.2_1/libexec/bin/python install /private/tmp/harlequin--pyarrow-20241129-4
==> python3.11 -m pip --python=/opt/homebrew/Cellar/harlequin/1.25.2_1/libexec/bin/python install /private/tmp/harlequin--Pygments-20241129-
==> python3.11 -m pip --python=/opt/homebrew/Cellar/harlequin/1.25.2_1/libexec/bin/python install /private/tmp/harlequin--pyperclip-20241129
==> python3.11 -m pip --python=/opt/homebrew/Cellar/harlequin/1.25.2_1/libexec/bin/python install /private/tmp/harlequin--questionary-202411
==> python3.11 -m pip --python=/opt/homebrew/Cellar/harlequin/1.25.2_1/libexec/bin/python install /private/tmp/harlequin--rich-20241129-4786
==> python3.11 -m pip --python=/opt/homebrew/Cellar/harlequin/1.25.2_1/libexec/bin/python install /private/tmp/harlequin--rich-click-2024112
==> python3.11 -m pip --python=/opt/homebrew/Cellar/harlequin/1.25.2_1/libexec/bin/python install /private/tmp/harlequin--shandy-sqlfmt-2024
==> python3.11 -m pip --python=/opt/homebrew/Cellar/harlequin/1.25.2_1/libexec/bin/python install /private/tmp/harlequin--textual-20241129-4
==> python3.11 -m pip --python=/opt/homebrew/Cellar/harlequin/1.25.2_1/libexec/bin/python install /private/tmp/harlequin--textual-fastdatata
==> python3.11 -m pip --python=/opt/homebrew/Cellar/harlequin/1.25.2_1/libexec/bin/python install /private/tmp/harlequin--textual-textarea-2
==> python3.11 -m pip --python=/opt/homebrew/Cellar/harlequin/1.25.2_1/libexec/bin/python install /private/tmp/harlequin--tomlkit-20241129-4
==> python3.11 -m pip --python=/opt/homebrew/Cellar/harlequin/1.25.2_1/libexec/bin/python install /private/tmp/harlequin--tqdm-20241129-4786
==> python3.11 -m pip --python=/opt/homebrew/Cellar/harlequin/1.25.2_1/libexec/bin/python install /private/tmp/harlequin--tree-sitter-202411
==> python3.11 -m pip --python=/opt/homebrew/Cellar/harlequin/1.25.2_1/libexec/bin/python install /private/tmp/harlequin--tree-sitter-langua
==> python3.11 -m pip --python=/opt/homebrew/Cellar/harlequin/1.25.2_1/libexec/bin/python install /private/tmp/harlequin--typing-extensions-
==> python3.11 -m pip --python=/opt/homebrew/Cellar/harlequin/1.25.2_1/libexec/bin/python install /private/tmp/harlequin--uc-micro-py-202411
==> python3.11 -m pip --python=/opt/homebrew/Cellar/harlequin/1.25.2_1/libexec/bin/python install /private/tmp/harlequin--wcwidth-20241129-4
==> python3.11 -m pip --python=/opt/homebrew/Cellar/harlequin/1.25.2_1/libexec/bin/python install /private/tmp/harlequin-20241129-47869-pvot
🍺  /opt/homebrew/Cellar/harlequin/1.25.2_1: 3,361 files, 101.6MB, built in 6 minutes 3 seconds
...
```

**Comment by mfinelli** [comment]
I think that this was fixed in https://github.com/Homebrew/homebrew-core/commit/4364f921e3411951fda2e535868f2095d8c56d6b

**Comment by tconbeer** [comment]
Thank you!

**Comment by heuermh** [comment]
Yes, I can confirm it works now.  Thank you @mfinelli @tconbeer!

```
$ brew uninstall harlequin
$ brew update
$ brew install harlequin
...
==> Installing harlequin
==> Pouring harlequin--1.25.2_1.arm64_sonoma.bottle.tar.gz
🍺  /opt/homebrew/Cellar/harlequin/1.25.2_1: 3,361 files, 101.9MB
```
