### ISSUE TITLE
Running inside codespaces: TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by matsonj** [tconbeer/harlequin#9]
I was trying to use this inside of my [nba-monte-carlo](https://github.com/matsonj/nba-monte-carlo) project.

I opened the codespace, ran ```pip install harlequin``` followed by ```cd data/data_catalog/```. If I think try to open my db with ```harlequin mdsbox.db```, I get the following error:

```
Traceback (most recent call last):
  File "/home/vscode/.local/bin/harlequin", line 5, in <module>
    from harlequin.cli import harlequin
  File "/home/vscode/.local/lib/python3.9/site-packages/harlequin/__init__.py", line 1, in <module>
    from harlequin.tui.app import Harlequin as Harlequin
  File "/home/vscode/.local/lib/python3.9/site-packages/harlequin/tui/app.py", line 13, in <module>
    from harlequin.tui.components import (
  File "/home/vscode/.local/lib/python3.9/site-packages/harlequin/tui/components/__init__.py", line 1, in <module>
    from harlequin.tui.components.code_editor import CodeEditor as CodeEditor
  File "/home/vscode/.local/lib/python3.9/site-packages/harlequin/tui/components/code_editor.py", line 4, in <module>
    from harlequin.tui.components.textarea import TextArea, TextInput
  File "/home/vscode/.local/lib/python3.9/site-packages/harlequin/tui/components/textarea.py", line 16, in <module>
    from harlequin.tui.components.error_modal import ErrorModal
  File "/home/vscode/.local/lib/python3.9/site-packages/harlequin/tui/components/error_modal.py", line 7, in <module>
    class ErrorModal(ModalScreen):
  File "/home/vscode/.local/lib/python3.9/site-packages/harlequin/tui/components/error_modal.py", line 13, in ErrorModal
    name: str | None = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by tconbeer** [comment]
I've been using the shorthand for union types (|), which is only supported on py3.10+. I don't have the python dependency labeled correctly in the package. 

I'll fix this since I know a lot of ppl are on earlier versions but you could also upgrade python if it's not too much trouble (famous last words)

**Comment by matsonj** [comment]
Yes I am good to test on 3.10. Will do so and report back :)
